export const API_CONSTANTS: any = {
  login: "Login/CLogin",
  /** will remove later */
  createStatus: "master/status",
  getstatus: "/master/statusList",
  createUsertype: 'master/usertype',
  createInquiryType: 'master/inquiryType',
  getinquirytypelist: "master/inquiryTypeList",
  getuserType: 'master/usertypelist',
  createuser: "/master/createuser",
  userlist: 'master/userList',
  userbyid: 'master/userList?email={email}',
  createinquiry: "/inquiry/createinquiry",
  inquirylist: "inquiry/inquirylist",
  deleteinquiry: "inquiry/delete/{id}",
  menuList: "panthermenuapi/DefaultMenuList?UserId=229",
  liveData: `VehicleList/SearchByVehicle/{id}`,
  forgotPasswordDetail:'Login/CforgotPassword/{userId}',
  dealerForgotPassword:'Login/DforgotPassword/{userId}',
  sendForgotEmail:'Login/SendEmail',
  sendForgotMobile:'Login/SendMessage',
  /** ------------- */
  vehicleList: 'VehicleList',
  vehicleListdetail: 'VehicleList/VehicleListV1',
  distanceReport: 'Distance/distanceReport',
  logout: 'Login/Logout',
  createGeofance: 'Geofence',
  updateGeofance: 'Geofence/{id}',
  geofanceList: 'Geofence',
  deleteGeofance: 'Geofence/{id}',
  getAddress: 'devicecheckapi/WeatherForecast/GetAddress?lat={lat}&lng={lng}' ,
  historydata: 'History/replayWithStop',
  adminHistorydata:'History/replayWithStop1',
  changePassword: 'password',
  dealerDetails: 'Dealer/GetDealerDetails',
  customerDetails: 'v1/CustomerUser/GetCustomerDetails',
  updateProfile: 'v1/Customer/UpdateCustomerProfile/{id}',
  updateVehcleType: 'v1/CustomerDevice/CustomerUpdateDevice/{id}',
  updateOverSpeed: 'v1/DeviceMetaData/UpdateSpeedLimit/{id}',
  updateOdometer:'v1/DeviceMetaData/UpdateOdometer/{id}',
  alertReport: 'Alerts?&lastTime={time}',
  dLogin: 'Login/DLogin',
  dayDistance:'VehicleList/daydistance_dash',
  /**-----Dealer and Reseller */

  getDealerList: 'v1/Reseller/Dropdown',
  customer: 'v1/Customer/{id}',
  customerVehicle :'VehicleList/{id}',
  resellerList:'Reseller',
  // tripReport: 'Trip',
  tripReport: 'Trip/TripReport',
  resselerById:'v1/Reseller/{id}',

  // admin part start
  addCustomer :'v1/Customer',
  addCustomerUser : 'v1/CustomerUser',
  adminProfile: 'Reseller/GetResellerProfile',
  getCoustomer : 'v1/Customer/{dealerId}/{customerId}',
  updateCustomer: 'v1/Customer/{customerId}',
  updateCustomerUser: 'v1/CustomerUser/{userId}',
  customerPlanPeriod: 'CustomerPlanPeriod',
  getPlan: 'CustomerPlan/{dealerId}/{customerId}',
  addCustomerPlan :'CustomerPlan',
  updateCustomerPlan: 'CustomerPlan/{planId}',
  userList: 'v1/CustomerUser/{dealerId}/{cusotmerId}',
  customerUser: 'CustomerUser/GetById/{cusotmerId}/{userId}',
  customerDevice: 'v1/CustomerDevice/{dealerId}/{customerId}' ,
  deviceMapping : 'DeviceMapping',
  selectedDevice: 'DeviceMapping/{userId}',
  deleteSubuser: 'DeviceMapping/{dealerId}/{cusId}/{subuserId}',
  deleteDevice: 'v1/CustomerDevice/{dealerId}/{cusId}/{deviceId}',
  pointSummaryList : 'Points/PointSummary',
  adminLiveVehicle: 'VehicleList/{vehicleId}',
  deviceType: "DeviceType",
  vehicleType:'VehicleType',
  operator: "Operator",
  device: "v1/CustomerDevice",
  updateDevice: 'v1/CustomerDevice/{id}',
  shiftCustomer: 'Move/Customer',
  balancePoint: 'Points/BalancePoint',
  checkBalance: 'Points/BalancePoint/{id}',
  lastSummary: 'Points/Last10Summary',
  profileDetail: 'Reseller/GetResellerProfile',
  adminProfileUpdate: 'Reseller/UpdateProfile/{id}',
  deviceById: 'v1/CustomerDevice/{id}/{customerId}/{deviceId}',
  deviceMetaData: 'v1/DeviceMetaData/{id}/{customerId}/{deviceId}',
  updateDeviceMetaData: 'v1/DeviceMetaData/{deviceId}',
  reseller :'Reseller',
  getResellerById: "Reseller/{id}",
  updateReseller : '/Reseller/{id}',
  DebitPoint: 'Points/DebitPoint',
  CreditPoint:'Points/CreditPoint',
  modifiedPassword:'Dealer/ChangePassword',
  moveDevice:'Move/Device',
  rechargePointValidity:'DeviceValidity/{deviceId}',
  updateRecharge:'DeviceValidity/{deviceId}',
  activatePoint:'Points/AllocateToDevice',
  getdevicemaker:'DeviceValidity/Devicemaker',
  getdevicetype :'DeviceValidity/Devicemaker/{id}',
  getdevicetypeById :'DeviceValidity/Devicemakerwithtype/{id}',
  devicetype:'DeviceValidity/Devicemakerwithtype',
  allReseller: 'VehicleList/Reseller/{id}',
  allResellerCount: 'VehicleList/Reseller/{id}/{rollId}',
  selectReseller : 'VehicleList/Reseller/Detailed/{id}/{resellerId}',
  selectResellerOverView : 'VehicleList/Reseller/Detailed/{id}/{resellerId}/{rollId}',
  selectDeviceSummary : 'VehicleList/Reseller/Detailed/{id}/{statusId}',
  customerDeviceSearch : 'CustomerDevice/OpenSearch/{deviceId}',
  duplicateDevice: 'v1/CustomerDevice/DuplicateDeviceId/0/{searchId}',
  deviceTimeValidity: 'DeviceValidity/DeviceValidity/{min}/{deviceId}',
  userSearch: 'CustomerUser/OpenSearch/{custmerId}',
  createFitment:'fitment',
  showFitment:'fitment/{id}',
  fitnmentImage:'fitment/PostFile/a',
  deviceListdetail:'v1/CustomerDevice/resellers/{id}/{role}',
  duplicateSubUser: 'CustomerUser/duplicate-login/0/{searchId}',
  deleteDeviceFitement: 'fitment/{deviceId}',
  addEditDeviceMaker:'Device/AddEditDeviceTypeMaster',
  deviceMasterList:'Device/GetDeviceTypeMaster',
  deviceTypeList:'Device/GetDeviceTypeChild',
  addEditDeviceType:'Device/AddEditDeviceTypeChild',
  alert :'Alert/GetAlertData',
  alertType: 'Alert/GetAlertType',
  alertSetting : 'Alerts/userId?UserId={userId}',
  alertsmapping :'Alerts/Alertsmapping',
  simOperator:'SIMCard/Basket/baskets',
  simOperatorStatus:'SIMCard/SIMCard/SIMDetail',
  simBillSummary:'SIMCard/SIMCard/SIMDetail_Dealerrwise',
  bulkUploadDevice:'UploadDeviceExcel/upload?customer_id={custmId}&uploadby_id=0',
  resellerEmployee:'Reseller/ResellerEmployee',
  getOdometerDetail :'Odometer/{id}',
  addOdometer :'Odometer',
  deviceLogData:'DeviceData/GetDeviceLog',
  lastlocationData  :'ShareLocation/GetLastLocation/{key}',
  bulkDeviceActivated:'v1/CustomerDevice/Active/{dealerId}/{customerId}',
  duplicateLoginId: 'v1/Customer/DuplicateCustomerLoginId',
  deviceDetail: 'DeviceData/GetdistanceReport',
  deviceCommandList:'Device/devicecommandlist',
  deviceMakerDropdown:'Comman/GetDeviceMakerList',
  deviceTypeDropdown:'Comman/GetDeviceTypeList',
  commandTypeDropdown:'Device/DeviceCommandType',
  addUpdateCommand:'Device/AddUpdateDeviceCommand',
  checkDetail:'UserToken/ValidateUserPassword',
  bulkModified:'Points/AllocateToDevicebulk'
};
